### ISSUE TITLE
Doesn't work on Secret Ninja Training School page

### ISSUE THREAD

**Issue by SundreamersCode** [mtkwock/Neopets-UserScripts#14]
Like the title says, it doesn't seem to work on the Secret Ninja Training School page. It doesn't show up on the list of scripts so maybe something is missing for that page? I included a screenshot of what it looks looks like on the Secret Ninja page vs Island training page.

Love this script! I train multiple pets so this will make things much easier :D

![Screenshot 2024-11-02 202425](https://github.com/user-attachments/assets/d6fc723c-00a3-4553-a522-cbcf050f7817)
![Screenshot 2024-11-02 202453](https://github.com/user-attachments/assets/010373bc-2b47-471e-babf-286f70862453)

**Comment by mtkwock** [comment]
Thanks for the comment!  It's true; I haven't been able to personally test this.  I can say that I made a typo when enabling it for Secret Ninja (And as I said, I can't test it myself yet x.x)

The correct link should be:

`// @match        https://www.neopets.com/island/fight_training.phtml?type=status*`
Instead of what I had before
`// @match        https://www.neopets.com/island/fight_training.phtml?status*`

You can probably patch this out yourself for now, but I will be pushing a fix soonish when I have a few more updates bundled!

**Comment by SundreamersCode** [comment]
That change worked! Thanks! :D
